import Head from 'next/head'
import Image,{ImageProps} from 'next/image'
import { Inter } from 'next/font/google'
import logo from '../public/logo.png'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="h-full">
      <Head >
        <title>Извиднички Одред Наум Наумовски-Борче</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="bg-[url('/homepage.jpg')]  bg-cover bg-center ... h-[929px] border-blue-400  border-8">
        <div>
      <Image 
         src={logo} alt="placeholder" className=" w-28 h-28 mr-2 p-3"
      />
    </div>
        <nav className="absolute top-0 right-0 mt-2 mr-2 p-5 font-serif text-lg ">
      <ul className="flex space-x-10 ">
        <li className="mr-6 text-white "><a href="#">За Нас</a></li>
        <li className="mr-6 text-white hover:underline"><a href="galery.html">Галерија</a></li>
        <li className="mr-6 text-white"><a href="#">Патеки</a></li>
        <li className="mr-6 text-white"><a href="#">Искуства</a></li>
        <li className="text-white"><a href="#">Контакт</a></li>
      </ul>
    </nav>
  
      <div className='absolute inset-0 flex items-center justify-center m-3.5'>
      <ul>
      <li className="text-white text-6xl text-center underline-offset-1 font-serif">Извиднички Одред  </li>
      <li className="text-white text-6xl text-center underline-offset-1 font-serif">Наум Наумовски- Борче </li>
      <li className="text-yellow-400 text-4xl text-center underline-offset-1 font-serif "> Создаваме подобар свет / Creating a better world</li>
      </ul>
      </div>
  
        </section>
      </main>
    </div>
  )
}
